spring.application.name=modelo_api_rest

# --- CONFIGURAÇÃO PADRÃO: H2 (Roda em qualquer máquina) ---
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# 1. Avisa o Hibernate para recriar as tabelas sempre que rodar o projeto
# (Ideal para ambiente de desenvolvimento com data.sql, assim evita dados duplicados)
spring.jpa.hibernate.ddl-auto=create

# 2. 🚨 A MÁGICA AQUI: Atrasa o data.sql para DEPOIS da criação das tabelas
spring.jpa.defer-datasource-initialization=true

# 3. Garante a execução do script SQL
spring.sql.init.mode=always

# --- MYSQL (Comentado para uso futuro) ---
# spring.datasource.url=jdbc:mysql://localhost:3306/db_projeto
# spring.datasource.username=root
# spring.datasource.password=1234
